version: "3.9"

services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: radius
      MYSQL_USER: radius
      MYSQL_PASSWORD: dalodbpass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./radius-mysql:/var/lib/mysql
    networks:
      - dalonet

  freeradius:
    build: ./FreeRadius
    container_name: freeradius_server
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: radius
      MYSQL_PASSWORD: dalodbpass
      MYSQL_DATABASE: radius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./clients.conf:/etc/freeradius/3.0/clients.conf
      - radius_data:/etc/freeradius
    networks:
      - dalonet

  php:
    build: ./Web
    container_name: php_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./Web:/var/www/html
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: radius
      MYSQL_PASSWORD: dalodbpass
      MYSQL_DATABASE: radius
    depends_on:
      - mysql
    networks:
      - dalonet

networks:
  dalonet:
    driver: bridge

volumes:
  radius_data:
