version: "3.9"

services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: radius
      MYSQL_USER: radius
      MYSQL_PASSWORD: dalodbpass
    ports:
      - "3306:3306"
    volumes:  
      - ./mysql-init:/docker-entrypoint-initdb.d   
    networks:
      - dalonet
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-p$MYSQL_ROOT_PASSWORD", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 5s
      retries: 5

  freeradius:
    build: ./FreeRadius
    restart: "no"
    container_name: freeradius_server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DEBUG: "true"
      MYSQL_HOST: mysql_server
      MYSQL_USER: radius
      MYSQL_PASSWORD: dalodbpass
      MYSQL_DATABASE: radius
      
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "3799:3799/udp"
    networks:
      - dalonet
    

  php:
    build: ./web
    container_name: php_web
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    environment:
      MYSQL_HOST: mysql_server
      MYSQL_USER: radius
      MYSQL_PASSWORD: dalodbpass
      MYSQL_DATABASE: radius
    networks:
      - dalonet

networks:
  dalonet:
    driver: bridge
